sudo: false
language: python
cache: pip
python:
- '3.8'
env:
- PACKAGES="Django~=2.2"
- PACKAGES="Django~=2.2 django-threadedcomments>=1.2"
- PACKAGES="Django~=3.0"
- PACKAGES="Django~=3.0 django-threadedcomments>=1.2"
- PACKAGES="Django~=3.1"
- PACKAGES="Django~=3.1 django-threadedcomments>=1.2"
- PACKAGES="Django~=3.2"
- PACKAGES="Django~=3.2 django-threadedcomments>=1.2"
- PACKAGES='https://github.com/django/django/archive/master.tar.gz'
matrix:
  allow_failures:
  - env: PACKAGES='https://github.com/django/django/archive/master.tar.gz'
before_install:
- pip install codecov
install:
- pip install -U pip wheel
- pip install $PACKAGES -e .
script:
- coverage run example/manage.py test
after_success:
- codecov
notifications:
  irc:
    channels:
    - irc.freenode.org#django-fluent
    template:
    - '%{repository}#%{build_number} (%{commit}) %{message}  --  %{build_url}'
    skip_join: true
  email:
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
  slack:
    secure: UQYHU07XN2kSAea1wFMMm9OsDJdavodhQsE8oT3SjxdXCbfBe/M1HXE8lbY2sZetWNiyQrZfodICDxhquQsNnUQ9IwMiSkWyofdT7rFA/2txPtf8bCnVMb0j0qJL+eKhFLBdtAEhi3PmuD2DqxcQxyz81enwtCk3vq8hzBEZu4I=
    on_success: never
    on_failure: always
